language: android

jdk: oraclejdk8

sudo: required # more memory
dist: trusty
group: deprecated-2017Q4

before_install:
  - yes | sdkmanager "platforms;android-28"

android:
  components:
    - tools
    - platform-tools
    - tools # called twice to get the newest android sdk tools
    - build-tools-28.0.3
    - android-28
    - extra-android-m2repository
    - extra-google-m2repository
    - sys-img-armeabi-v7a-google_apis-28 # emulator

env:
  - FLAVOR="openhpi"
  - FLAVOR="opensap"
  - FLAVOR="moochouse"
  - FLAVOR="openwho"

before_script: # Emulator Management: Create, Start and Wait
  - echo no | android create avd --force -n test -t android-28 --abi google_apis/armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell settings put global window_animation_scale 0 &
  - adb shell settings put global transition_animation_scale 0 &
  - adb shell settings put global animator_duration_scale 0 &
  - adb shell input keyevent 82 &

script:
   - ./gradlew assemble${FLAVOR}Debug test${FLAVOR}DebugUnitTest connected${FLAVOR}DebugAndroidTest
