language: android
android:
  components:
    - tools
    - platform-tools
    - tools # called twice to get the newest android sdk tools
    - build-tools-26.0.2
    - android-27
    - extra-android-m2repository
    - extra-google-m2repository

jdk:
  - oraclejdk8

env:
  - FLAVOR="openHPI"
  - FLAVOR="openSAP"
  - FLAVOR="moocHouse"
  - FLAVOR="openWHO"

sudo: required # more memory

script:
   - >
       ./gradlew assemble${FLAVOR}RegularDebug test${FLAVOR}RegularDebugUnitTest connected${FLAVOR}RegularDebugAndroidTest
       && ./gradlew assemble${FLAVOR}RegularRelease test${FLAVOR}RegularReleaseUnitTest
