language: android
android:
  components:
    - platform-tools
    - tools
    - build-tools-25.0.3
    - android-25
    - extra-android-m2repository
    - extra-google-m2repository

jdk:
  - oraclejdk8

env:
  - FLAVOR="openHPI"
  - FLAVOR="openSAP"
  - FLAVOR="moocHouse"
  - FLAVOR="openWHO"

script:
   - >
       ./gradlew assemble${FLAVOR}Debug test${FLAVOR}DebugUnitTest connected${FLAVOR}DebugAndroidTest
       && ./gradlew assemble${FLAVOR}Release test${FLAVOR}ReleaseUnitTest